# Use uma imagem base do Node.js
FROM mcr.microsoft.com/playwright:v1.45.3-jammy

# Define o diretório de trabalho
WORKDIR /app

# Copie o arquivo de configuração do npm e o arquivo package-lock.json
COPY package*.json ./

# Instale as dependências do npm
RUN npm install

# Copie o restante do código do projeto
COPY . .

# Comando para rodar os testes
CMD ["npm", "run", "test"]
