name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Pipeline de testes
    if: ${{ success() }}
    needs: sonarcloud
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright
        run: npm i -D allure-playwright

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Download Allure history
        if: always()
        continue-on-error: true
        run: |
          REPOSITORY=${{ github.repository }}
          REPOSITORY_OWNER=${{ github.repository_owner }}
          REPOSITORY_NAME=${REPOSITORY#$REPOSITORY_OWNER/}
        
          wget --recursive --no-parent --convert-links --page-requisites -P history \
          "https://$REPOSITORY_OWNER.github.io/$REPOSITORY_NAME/history"

    # Cria diretório para histórico se não existir
      - name: Create Allure history directory
        if: always()
        run: |
          mkdir -p allure-results/history
          mkdir -p allure-report/history

    # Copia histórico anterior se existir
      - name: Copy Allure history
        if: always()
        continue-on-error: true
        run: |
          cp -r history/*/history/* allure-results/history/ || true

      - name: Run Playwright tests
        run: npm run test
        env:
          PLAYWRIGHT_HTML_REPORT: playwright-report
          ALLURE_RESULTS_DIR: allure-results

    # Gera relatório com histórico
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean

    # Cria diretório com data para histórico
      - name: Create report directory with date
        if: always()
        run: |
          DATE_WITH_TIME=$(date "+%Y%m%d_%H%M%S")
          mkdir -p report_history/$DATE_WITH_TIME
          cp -r allure-report/* report_history/$DATE_WITH_TIME/
        
    # Deploy para GitHub Pages mantendo histórico
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_branch: gh-pages
          publish_dir: ./report_history
          keep_files: true
