name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests:
    name: Pipeline de testes
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: ${{ success() }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright
        run: npm i -D allure-playwright

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run tests
        run: npx playwright test

      - name: Generate and Publish Allure Report
        uses: Valiantsin2021/allure-shard-results-publish@1.0.5
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          results-pattern: 'allure-results-*'
          results-directory: 'combined-allure-results'
          report-directory: 'allure-report'
          history-directory: 'allure-history'
          gh-pages: 'gh-pages'
          gh-pages-branch: 'gh-pages'
          report-title: 'My Test Report'
          retention-days: '10'
          publish-to-pages: 'true'
          fail-on-empty-results: 'false'
          add-env: 'true'