name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Pipeline de testes
    if: ${{ success() }}
    needs: sonarcloud
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright
        run: npm i -D allure-playwright

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-results/
          retention-days: 30

  notification:
    if: ${{ failure() }}
    name: Notification
    needs: test
    uses: cinotify/github-action@main
    with:
      to: 'br.avila.l@gmail.com'
      subject: 'Falha nos testes'
      body: '<em>Falha na execução dos testes.</em>'
      type: 'text/html'
      attachment: 'artifacts.zip'
