name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Pipeline de testes
    if: ${{ success() }}
    needs: sonarcloud
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright
        run: npm i -D allure-playwright

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-results/
          retention-days: 30

  notification:
    name: CINotify Email
    needs: test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      uses: cinotify/github-action@v1.6.0
      with:
        to: 'br.avila.l@gmail.com'
        subject: 'Falha nos testes - Workflow: ${{ github.workflow }}'
        body: |
          <html>
            <body>
              <h2>Falha na execução dos testes</h2>
              <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
              <p><strong>Job:</strong> ${{ github.job }}</p>
              <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
              <p><strong>Commit:</strong> ${{ github.sha }}</p>
              <p><strong>Autor do commit:</strong> ${{ github.actor }}</p>
              <p><strong>Mensagem do commit:</strong> ${{ github.event.head_commit.message }}</p>
              <p>Você pode visualizar os detalhes do workflow no seguinte link:</p>
              <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Clique aqui para ver os logs completos</a></p>
              <p><em>Este e-mail contém o relatório da falha nos testes e os artefatos anexados.</em></p>
           </body>
          </html>
        type: 'text/html'
